name: IPTV Optimize
on: [push] # 仅推送触发，简化测试
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.13' }
      - run: |
          sudo apt update
          sudo apt install ffmpeg
          pip install -r requirements.txt
      - run: python main.py
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add gd/output/result.txt
          git commit -m "更新直播源" || echo "无更改"
          git push
